/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

/**
 *
 * @author Ritika
 */
public class decks extends javax.swing.JFrame {

    /**
     * Creates new form decks
     */
    public decks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ritika\\Desktop\\highway-road-marking-horizontal-straight-asphalt-vector-21826047.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel3.setBackground(new java.awt.Color(50, 205, 50));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ritika\\Desktop\\highway-road-marking-horizontal-straight-asphalt-vector-21826047.jpg")); // NOI18N
        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(50, 205, 50));
        jButton1.setText("Slot 1");
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 60, 130, 47);

        jButton2.setBackground(new java.awt.Color(50, 205, 50));
        jButton2.setText("Slot 6");
        jPanel1.add(jButton2);
        jButton2.setBounds(0, 180, 130, 47);

        jButton3.setBackground(new java.awt.Color(50, 205, 50));
        jButton3.setText("Slot 11");
        jPanel1.add(jButton3);
        jButton3.setBounds(0, 300, 129, 47);

        jButton4.setBackground(new java.awt.Color(50, 205, 50));
        jButton4.setText("Slot 16");
        jPanel1.add(jButton4);
        jButton4.setBounds(0, 420, 129, 47);

        jButton5.setBackground(new java.awt.Color(50, 205, 50));
        jButton5.setText("Slot 21");
        jPanel1.add(jButton5);
        jButton5.setBounds(0, 550, 129, 47);

        jButton6.setBackground(new java.awt.Color(50, 205, 50));
        jButton6.setText("Slot 2");
        jPanel1.add(jButton6);
        jButton6.setBounds(200, 60, 130, 47);

        jButton7.setBackground(new java.awt.Color(30, 144, 255));
        jButton7.setText("Slot 3");
        jPanel1.add(jButton7);
        jButton7.setBounds(420, 60, 130, 47);

        jButton8.setBackground(new java.awt.Color(30, 144, 255));
        jButton8.setText("Slot 4");
        jPanel1.add(jButton8);
        jButton8.setBounds(650, 60, 130, 47);

        jButton9.setBackground(new java.awt.Color(50, 205, 50));
        jButton9.setText("Slot 5");
        jPanel1.add(jButton9);
        jButton9.setBounds(850, 60, 130, 47);

        jButton10.setBackground(new java.awt.Color(50, 205, 50));
        jButton10.setText("Slot 7");
        jPanel1.add(jButton10);
        jButton10.setBounds(200, 180, 130, 47);

        jButton11.setBackground(new java.awt.Color(50, 205, 50));
        jButton11.setText("Slot 8");
        jPanel1.add(jButton11);
        jButton11.setBounds(420, 180, 130, 47);

        jButton12.setBackground(new java.awt.Color(50, 205, 50));
        jButton12.setText("Slot 9");
        jPanel1.add(jButton12);
        jButton12.setBounds(650, 180, 130, 47);

        jButton13.setBackground(new java.awt.Color(50, 205, 50));
        jButton13.setText("Slot 10");
        jPanel1.add(jButton13);
        jButton13.setBounds(850, 180, 129, 47);

        jButton14.setBackground(new java.awt.Color(50, 205, 50));
        jButton14.setText("Slot 12");
        jPanel1.add(jButton14);
        jButton14.setBounds(200, 300, 129, 47);

        jButton15.setBackground(new java.awt.Color(50, 205, 50));
        jButton15.setText("Slot 13");
        jPanel1.add(jButton15);
        jButton15.setBounds(420, 300, 129, 47);

        jButton16.setBackground(new java.awt.Color(50, 205, 50));
        jButton16.setText("Slot 14");
        jPanel1.add(jButton16);
        jButton16.setBounds(650, 300, 129, 47);

        jButton17.setBackground(new java.awt.Color(50, 205, 50));
        jButton17.setText("Slot 15");
        jPanel1.add(jButton17);
        jButton17.setBounds(850, 300, 130, 47);

        jButton18.setBackground(new java.awt.Color(50, 205, 50));
        jButton18.setText("Slot 17");
        jPanel1.add(jButton18);
        jButton18.setBounds(200, 420, 129, 47);

        jButton19.setBackground(new java.awt.Color(50, 205, 50));
        jButton19.setText("Slot 18");
        jPanel1.add(jButton19);
        jButton19.setBounds(420, 420, 129, 47);

        jButton20.setBackground(new java.awt.Color(50, 205, 50));
        jButton20.setText("Slot 19");
        jPanel1.add(jButton20);
        jButton20.setBounds(650, 420, 129, 47);

        jButton21.setBackground(new java.awt.Color(50, 205, 50));
        jButton21.setText("Slot 20");
        jPanel1.add(jButton21);
        jButton21.setBounds(850, 420, 130, 47);

        jButton22.setBackground(new java.awt.Color(50, 205, 50));
        jButton22.setText("Slot 22");
        jPanel1.add(jButton22);
        jButton22.setBounds(200, 550, 129, 47);

        jButton23.setBackground(new java.awt.Color(30, 144, 255));
        jButton23.setText("Slot 23");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton23);
        jButton23.setBounds(420, 550, 129, 47);

        jButton24.setBackground(new java.awt.Color(30, 144, 255));
        jButton24.setText("Slot 24");
        jPanel1.add(jButton24);
        jButton24.setBounds(650, 550, 129, 47);

        jButton25.setBackground(new java.awt.Color(50, 205, 50));
        jButton25.setText("Slot 25");
        jPanel1.add(jButton25);
        jButton25.setBounds(850, 550, 130, 47);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ritika\\Desktop\\highway-road-marking-horizontal-straight-asphalt-vector-21826047.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-10, -30, 990, 1040);

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("EXIT");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(570, 0, 68, 39);

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("EXIT");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(570, 630, 68, 39);

        jButton26.setBackground(new java.awt.Color(50, 205, 50));
        jButton26.setText("jButton26");
        jPanel1.add(jButton26);
        jButton26.setBounds(1000, 180, 100, 47);

        jButton27.setBackground(new java.awt.Color(201, 21, 21));
        jButton27.setText("jButton27");
        jPanel1.add(jButton27);
        jButton27.setBounds(1000, 300, 100, 47);

        jButton28.setBackground(new java.awt.Color(30, 144, 255));
        jButton28.setText("jButton28");
        jPanel1.add(jButton28);
        jButton28.setBounds(1000, 420, 100, 47);

        jLabel6.setText("Available");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(1130, 180, 125, 39);

        jLabel7.setText("Booked");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(1130, 300, 101, 39);

        jLabel8.setText("Disabled");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(1130, 430, 120, 39);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(decks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(decks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(decks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(decks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new decks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
